[package]
name = "simdeez"
version = "1.0.0"
authors = ["Jack Mott <jack.mott@gmail.com>"]
description = "SIMD library to abstract over different instruction sets and widths"
license = "Apache-2.0/MIT"
documentation = "https://docs.rs/simdeez/"
readme = "README.md"
keywords = ["SIMD", "avx2", "sse", "performance","no_std"]
repository = "https://github.com/jackmott/simdeez"
categories = ["hardware-support","science","game-engines"]
edition="2018"

[features]
sleef = ["sleef-sys"]

[dependencies]
paste = "0.1.6"
cfg-if = "0.1.10"

# To build this, we need nightly, cmake installed, and clang dlls in the clang dll path
# Use Octasine branch which supports static linking and alwys generating SSE and AVX instructions
[dependencies.sleef-sys]
git = 'https://github.com/greatest-ape/sleef-sys.git'
branch = "octasine"
features = ["static"]
optional=true

[dev-dependencies]
criterion = "0.3.0"
rand = "0.7.2"
[[bench]]
name = "benchmarks"
harness = false